#ifndef FNAF_ADVANCE_ROOM_NAMES_H
#define FNAF_ADVANCE_ROOM_NAMES_H

enum RoomNames {
    ROOM_STAGE, ROOM_DINING, ROOM_PIRATE, ROOM_WEST, ROOM_WEST_CORNER,
    ROOM_CLOSET, ROOM_EAST, ROOM_EAST_CORNER, ROOM_BACKSTAGE, ROOM_KITCHEN, ROOM_RESTROOMS
};


#endif //FNAF_ADVANCE_ROOM_NAMES_H
